server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test16?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: ytt19990813
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL


mybatis-plus:
  #启动时关闭banner
  global-config:
    banner: false
  type-aliases-package: work.xiaoying.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #全局映射器启用缓存
    cache-enabled: true
    #允许JDBC支持自动生成主键
    use-generated-keys: true
    #设置默认的执行器
    #simple 普通的执行器
    #reuse 执行器会重用预处理语句prepared statements
    #batch 执行器将重用语句并执行批量更新
    default-executor-type: simple
    #执行mybatis所用的日志为slf4j
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    work.xiaoying.controller: debug
    org.springframework: warn
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{20} - [%method,%line] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{20} - [%method,%line] - %msg%n"
  file:
    name: ./logs/system.log
  charset:
    console: UTF-8
    file: UTF-8
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 10MB


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true



